// <auto-generated />
using System;
using Asset.Variations.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asset.Variations.Data.Migrations
{
    [DbContext(typeof(AssetVariationDbContext))]
    partial class AssetVariationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AI")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asset.Variations.Data.Models.AssetVariation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("Dia");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.Property<float>("VariacaoDMenosUm")
                        .HasColumnType("real")
                        .HasColumnName("VariacaoDMenosUm");

                    b.Property<float>("VariacaoDPrimeiraData")
                        .HasColumnType("real")
                        .HasColumnName("VariacaoDPrimeiraData");

                    b.HasKey("Id");

                    b.ToTable("AssetVariation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
